// 難読漢字30問（hint = 読みがな）
export const nandoku = [
  { name: "蒲公英", romaji: "tanpopo", hint: "読み: たんぽぽ" },
  { name: "紫陽花", romaji: "ajisai", hint: "読み: あじさい" },
  { name: "向日葵", romaji: "himawari", hint: "読み: ひまわり" },
  { name: "秋刀魚", romaji: "sanma", hint: "読み: さんま" },
  { name: "海月", romaji: "kurage", hint: "読み: くらげ" },
  { name: "心太", romaji: "tokoroten", hint: "読み: ところてん" },
  { name: "雲丹", romaji: "uni", hint: "読み: うに" },
  { name: "烏賊", romaji: "ika", hint: "読み: いか" },
  { name: "章魚", romaji: "tako", hint: "読み: たこ" },
  { name: "山葵", romaji: "wasabi", hint: "読み: わさび" },
  { name: "生姜", romaji: "shouga", hint: "読み: しょうが" },
  { name: "蒟蒻", romaji: "konnnyaku", hint: "読み: こんにゃく" },
  { name: "南瓜", romaji: "kabocha", hint: "読み: かぼちゃ" },
  { name: "胡瓜", romaji: "kyuuri", hint: "読み: きゅうり" },
  { name: "玉蜀黍", romaji: "toumorokoshi", hint: "読み: とうもろこし" },
  { name: "檸檬", romaji: "remon", hint: "読み: れもん" },
  { name: "葡萄", romaji: "budou", hint: "読み: ぶどう" },
  { name: "林檎", romaji: "ringo", hint: "読み: りんご" },
  { name: "蜜柑", romaji: "mikan", hint: "読み: みかん" },
  { name: "無花果", romaji: "ichijiku", hint: "読み: いちじく" },
  { name: "枇杷", romaji: "biwa", hint: "読み: びわ" },
  { name: "栗鼠", romaji: "risu", hint: "読み: りす" },
  { name: "駱駝", romaji: "rakuda", hint: "読み: らくだ" },
  { name: "麒麟", romaji: "kirin", hint: "読み: きりん" },
  { name: "梟", romaji: "fukurou", hint: "読み: ふくろう" },
  { name: "燕", romaji: "tsubame", hint: "読み: つばめ" },
  { name: "蝸牛", romaji: "katatsumuri", hint: "読み: かたつむり" },
  { name: "蜻蛉", romaji: "tonbo", hint: "読み: とんぼ" },
  { name: "河豚", romaji: "fugu", hint: "読み: ふぐ" },
  { name: "土筆", romaji: "tsukushi", hint: "読み: つくし" },
];
