// ことわざ30問（hint = 意味）
// ローマ字は かな準拠。「ん」は母音・y・な行の前では "nn"、それ以外は "n"
export const kotowaza = [
  { name: "猿も木から落ちる", romaji: "sarumokikaraochiru", hint: "どんな名人でも失敗することがある" },
  { name: "石の上にも三年", romaji: "ishinouenimosannnen", hint: "辛抱強く続ければいつか成功する" },
  { name: "急がば回れ", romaji: "isogabamaware", hint: "急ぐときこそ安全確実な道を選べ" },
  { name: "犬も歩けば棒に当たる", romaji: "inumoarukebabouniataru", hint: "行動すれば思わぬ幸運に出会うこともある" },
  { name: "花より団子", romaji: "hanayoridango", hint: "風流よりも実利を取ること" },
  { name: "七転び八起き", romaji: "nanakorobiyaoki", hint: "何度失敗してもくじけず立ち上がること" },
  { name: "猫に小判", romaji: "nekonikoban", hint: "価値のわからない者には宝も無意味" },
  { name: "馬の耳に念仏", romaji: "umanomimininenbutsu", hint: "いくら意見しても効き目がないこと" },
  { name: "塵も積もれば山となる", romaji: "chirimotsumorebayamatonaru", hint: "小さなものも積み重なれば大きくなる" },
  { name: "石橋を叩いて渡る", romaji: "ishibashiwotataitewataru", hint: "用心の上にも用心を重ねること" },
  { name: "蛙の子は蛙", romaji: "kaerunokohakaeru", hint: "子は親に似るものだ" },
  { name: "果報は寝て待て", romaji: "kahouhanetemate", hint: "幸運は焦らずに待つのがよい" },
  { name: "木を見て森を見ず", romaji: "kiwomitemoriwomizu", hint: "細部にとらわれて全体を見失うこと" },
  { name: "転ばぬ先の杖", romaji: "korobanusakinotsue", hint: "失敗しないよう前もって準備すること" },
  { name: "好きこそ物の上手なれ", romaji: "sukikosomononojouzunare", hint: "好きなことは自然に上達するものだ" },
  { name: "急いては事を仕損じる", romaji: "seitehakotowoshisonjiru", hint: "焦ると失敗しやすいものだ" },
  { name: "立つ鳥跡を濁さず", romaji: "tatsutoriatowonigosazu", hint: "去り際は美しくあるべきだ" },
  { name: "灯台下暗し", romaji: "toudaimotokurashi", hint: "身近なことはかえって気づきにくい" },
  { name: "泣きっ面に蜂", romaji: "nakittsuranihachi", hint: "不運の上にさらに不運が重なること" },
  { name: "情けは人の為ならず", romaji: "nasakehahitonotamenarazu", hint: "人への親切はやがて自分に返ってくる" },
  { name: "論より証拠", romaji: "ronnyorishouko", hint: "議論するより証拠を示すのが早い" },
  { name: "百聞は一見にしかず", romaji: "hyakubunhaikkennnishikazu", hint: "何度も聞くより一度見るほうが確かだ" },
  { name: "覆水盆に返らず", romaji: "fukusuibonnnikaerazu", hint: "一度したことは取り返しがつかない" },
  { name: "良薬は口に苦し", romaji: "ryouyakuhakuchininigashi", hint: "ためになる忠告ほど聞くのがつらい" },
  { name: "三人寄れば文殊の知恵", romaji: "sannninnyorebamonjunochie", hint: "凡人でも三人集まればよい知恵が出る" },
  { name: "早起きは三文の徳", romaji: "hayaokihasanmonnnotoku", hint: "早起きするとよいことがある" },
  { name: "雨降って地固まる", romaji: "amefuttejikatamaru", hint: "もめごとの後はかえって安定するものだ" },
  { name: "井の中の蛙大海を知らず", romaji: "inonakanokawazutaikaiwoshirazu", hint: "狭い世界しか知らず広い世界を知らないこと" },
  { name: "能ある鷹は爪を隠す", romaji: "nouarutakahatsumewokakusu", hint: "実力のある者ほどそれを見せびらかさない" },
  { name: "二兎を追う者は一兎をも得ず", romaji: "nitowooumonohaittowomoezu", hint: "欲張って両方狙うとどちらも失敗する" },
];
