// 四字熟語30問（hint = 意味）
export const yojijukugo = [
  { name: "一石二鳥", romaji: "issekinichou", hint: "一つの行動で二つの利益を得ること" },
  { name: "十人十色", romaji: "juunintoiro", hint: "人それぞれ好みや考えが違うこと" },
  { name: "以心伝心", romaji: "ishindenshin", hint: "言葉にしなくても心が通じ合うこと" },
  { name: "温故知新", romaji: "onkochishin", hint: "昔のことを学び新しい知識を得ること" },
  { name: "花鳥風月", romaji: "kachoufuugetsu", hint: "自然の美しい景色や風流な遊び" },
  { name: "起死回生", romaji: "kishikaisei", hint: "絶望的な状況を立て直すこと" },
  { name: "疑心暗鬼", romaji: "gishinnanki", hint: "疑い出すと何でも不安になること" },
  { name: "弱肉強食", romaji: "jakunikukyoushoku", hint: "強い者が弱い者を征服して栄えること" },
  { name: "単刀直入", romaji: "tantouchokunyuu", hint: "前置きなしにいきなり本題に入ること" },
  { name: "日進月歩", romaji: "nisshingeppo", hint: "絶え間なく速く進歩すること" },
  { name: "半信半疑", romaji: "hanshinhangi", hint: "半分信じて半分疑うこと" },
  { name: "美辞麗句", romaji: "bijireiku", hint: "うわべだけ美しく飾った言葉" },
  { name: "不言実行", romaji: "fugenjikkou", hint: "あれこれ言わずに黙って実行すること" },
  { name: "本末転倒", romaji: "honmatsutentou", hint: "大事なことと些細なことを取り違えること" },
  { name: "無我夢中", romaji: "mugamuchuu", hint: "物事に熱中して我を忘れること" },
  { name: "明鏡止水", romaji: "meikyoushisui", hint: "邪念がなく澄み切った心境" },
  { name: "優柔不断", romaji: "yuujuufudan", hint: "ぐずぐずして決断できないこと" },
  { name: "臨機応変", romaji: "rinkiouhen", hint: "状況に応じて適切に対処すること" },
  { name: "一期一会", romaji: "ichigoichie", hint: "一生に一度だけの機会" },
  { name: "危機一髪", romaji: "kikiippatsu", hint: "髪の毛一本ほどの差まで危険が迫ること" },
  { name: "自画自賛", romaji: "jigajisan", hint: "自分で自分を褒めること" },
  { name: "四苦八苦", romaji: "shikuhakku", hint: "非常に苦労すること" },
  { name: "七転八倒", romaji: "shichitenbattou", hint: "苦しんで転げ回ること" },
  { name: "縦横無尽", romaji: "juuoumujin", hint: "思う存分自由自在に行動すること" },
  { name: "泰然自若", romaji: "taizenjijaku", hint: "落ち着いていて物事に動じないさま" },
  { name: "大器晩成", romaji: "taikibansei", hint: "大人物は時間をかけて大成すること" },
  { name: "電光石火", romaji: "denkousekka", hint: "稲妻のように極めて素早いこと" },
  { name: "東奔西走", romaji: "touhonseisou", hint: "あちこち忙しく走り回ること" },
  { name: "付和雷同", romaji: "fuwaraidou", hint: "自分の考えがなく他人に同調すること" },
  { name: "五里霧中", romaji: "gorimuchuu", hint: "状況がつかめず方針が立たないこと" },
];
