// 12星座（黄道十二宮）
export const zodiacSigns = [
  { name: "おひつじ座", romaji: "ohitsujiza", hint: "3/21〜4/19" },
  { name: "おうし座", romaji: "oushiza", hint: "4/20〜5/20" },
  { name: "ふたご座", romaji: "futagoza", hint: "5/21〜6/21" },
  { name: "かに座", romaji: "kaniza", hint: "6/22〜7/22" },
  { name: "しし座", romaji: "shishiza", hint: "7/23〜8/22" },
  { name: "おとめ座", romaji: "otomeza", hint: "8/23〜9/22" },
  { name: "てんびん座", romaji: "tenbinza", hint: "9/23〜10/23" },
  { name: "さそり座", romaji: "sasoriza", hint: "10/24〜11/22" },
  { name: "いて座", romaji: "iteza", hint: "11/23〜12/21" },
  { name: "やぎ座", romaji: "yagiza", hint: "12/22〜1/19" },
  { name: "みずがめ座", romaji: "mizugameza", hint: "1/20〜2/18" },
  { name: "うお座", romaji: "uoza", hint: "2/19〜3/20" },
];

// 88星座
export const constellations = [
  { name: "アンドロメダ座", romaji: "andoromedaza" },
  { name: "いっかくじゅう座", romaji: "ikkakujuuza" },
  { name: "いて座", romaji: "iteza" },
  { name: "いるか座", romaji: "irukaza" },
  { name: "インディアン座", romaji: "indeianza" },
  { name: "うお座", romaji: "uoza" },
  { name: "うさぎ座", romaji: "usagiza" },
  { name: "うしかい座", romaji: "ushikaiza" },
  { name: "うみへび座", romaji: "umihebiza" },
  { name: "エリダヌス座", romaji: "eridansuza" },
  { name: "おうし座", romaji: "oushiza" },
  { name: "おおいぬ座", romaji: "ooinuza" },
  { name: "おおかみ座", romaji: "ookamiza" },
  { name: "おおぐま座", romaji: "oogumaza" },
  { name: "おとめ座", romaji: "otomeza" },
  { name: "おひつじ座", romaji: "ohitsujiza" },
  { name: "オリオン座", romaji: "orionza" },
  { name: "がか座", romaji: "gakaza" },
  { name: "カシオペヤ座", romaji: "kashiopeyaza" },
  { name: "かじき座", romaji: "kajikiza" },
  { name: "かに座", romaji: "kaniza" },
  { name: "かみのけ座", romaji: "kaminokeza" },
  { name: "カメレオン座", romaji: "kamereonza" },
  { name: "からす座", romaji: "karasuza" },
  { name: "かんむり座", romaji: "kanmuriza" },
  { name: "きょしちょう座", romaji: "kyoshichouza" },
  { name: "ぎょしゃ座", romaji: "gyoshaza" },
  { name: "きりん座", romaji: "kirinza" },
  { name: "くじゃく座", romaji: "kujakuza" },
  { name: "くじら座", romaji: "kujiraz" },
  { name: "ケフェウス座", romaji: "kefeusuza" },
  { name: "ケンタウルス座", romaji: "kentaurusuza" },
  { name: "けんびきょう座", romaji: "kenbikyouza" },
  { name: "こいぬ座", romaji: "koinuza" },
  { name: "こうま座", romaji: "koumaza" },
  { name: "こぎつね座", romaji: "kogitsuneza" },
  { name: "こぐま座", romaji: "kogumaza" },
  { name: "コップ座", romaji: "koppuza" },
  { name: "こと座", romaji: "kotoza" },
  { name: "コンパス座", romaji: "konpasuza" },
  { name: "さいだん座", romaji: "saidanza" },
  { name: "さそり座", romaji: "sasoriza" },
  { name: "さんかく座", romaji: "sankakuza" },
  { name: "しし座", romaji: "shishiza" },
  { name: "じょうぎ座", romaji: "jougiza" },
  { name: "たて座", romaji: "tateza" },
  { name: "つる座", romaji: "tsuruza" },
  { name: "テーブルさん座", romaji: "teeburusanza" },
  { name: "てんびん座", romaji: "tenbinza" },
  { name: "とかげ座", romaji: "tokageza" },
  { name: "とけい座", romaji: "tokeiza" },
  { name: "とびうお座", romaji: "tobiuoza" },
  { name: "とも座", romaji: "tomoza" },
  { name: "はえ座", romaji: "haeza" },
  { name: "はくちょう座", romaji: "hakuchouza" },
  { name: "はちぶんぎ座", romaji: "hachibungiza" },
  { name: "はと座", romaji: "hatoza" },
  { name: "ふうちょう座", romaji: "fuuchouza" },
  { name: "ふたご座", romaji: "futagoza" },
  { name: "ペガスス座", romaji: "pegasususa" },
  { name: "へび座", romaji: "hebiza" },
  { name: "へびつかい座", romaji: "hebitsukaiza" },
  { name: "ヘルクレス座", romaji: "herukuresuza" },
  { name: "ペルセウス座", romaji: "peruseusuza" },
  { name: "ほ座", romaji: "hoza" },
  { name: "ぼうえんきょう座", romaji: "bouenkyouza" },
  { name: "ほうおう座", romaji: "hououza" },
  { name: "ポンプ座", romaji: "ponpuza" },
  { name: "みずがめ座", romaji: "mizugameza" },
  { name: "みずへび座", romaji: "mizuhebiza" },
  { name: "みなみじゅうじ座", romaji: "minamijuujiza" },
  { name: "みなみのうお座", romaji: "minaminouoza" },
  { name: "みなみのかんむり座", romaji: "minaminokanmuriza" },
  { name: "みなみのさんかく座", romaji: "minaminosankakuza" },
  { name: "や座", romaji: "yaza" },
  { name: "やぎ座", romaji: "yagiza" },
  { name: "やまねこ座", romaji: "yamanekoza" },
  { name: "らしんばん座", romaji: "rashinbanza" },
  { name: "りゅう座", romaji: "ryuuza" },
  { name: "りゅうこつ座", romaji: "ryuukotsaza" },
  { name: "りょうけん座", romaji: "ryoukenza" },
  { name: "レチクル座", romaji: "rechikuruza" },
  { name: "ろ座", romaji: "roza" },
  { name: "ろくぶんぎ座", romaji: "rokubungiza" },
  { name: "わし座", romaji: "washiza" },
];
